"""add_submission_content_to_verifications

Revision ID: 117a31494858
Revises: 80e90e4e0be5
Create Date: 2026-09-17 11:17:18.209679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117a31494858'
down_revision: Union[str, Sequence[str], None] = '80e90e4e0be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('submission_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verifications', 'submission_content')
    # ### end Alembic commands ###
