"""add resume_text to applications table

Revision ID: 4642d6602ccc
Revises: d83ca21ca4f1
Create Date: 2026-09-16 00:03:47.476379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4642d6602ccc'
down_revision: Union[str, Sequence[str], None] = 'd83ca21ca4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'resume_text')
    # ### end Alembic commands ###
