"""create_interview_rounds_and_templates_tables

Revision ID: b6e5b6cd982f
Revises: 2491a4136c44
Create Date: 2026-09-20 13:16:54.856853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e5b6cd982f'
down_revision: Union[str, Sequence[str], None] = '2491a4136c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'sequence', name='uq_job_round_sequence')
    )
    op.create_index(op.f('ix_interview_rounds_job_id'), 'interview_rounds', ['job_id'], unique=False)
    op.create_table('interview_question_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=True),
    sa.Column('question_intent', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('max_followups', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'sequence', name='uq_round_template_sequence')
    )
    op.create_index(op.f('ix_interview_question_templates_capability_id'), 'interview_question_templates', ['capability_id'], unique=False)
    op.create_index(op.f('ix_interview_question_templates_round_id'), 'interview_question_templates', ['round_id'], unique=False)
    op.add_column('interview_sessions', sa.Column('current_round_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_interview_sessions_current_round_id_interview_rounds', 'interview_sessions', 'interview_rounds', ['current_round_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_interview_sessions_current_round_id_interview_rounds', 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'current_round_id')
    op.drop_index(op.f('ix_interview_question_templates_round_id'), table_name='interview_question_templates')
    op.drop_index(op.f('ix_interview_question_templates_capability_id'), table_name='interview_question_templates')
    op.drop_table('interview_question_templates')
    op.drop_index(op.f('ix_interview_rounds_job_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    # ### end Alembic commands ###
