"""create email_connections table

Revision ID: e0a0102b1fba
Revises: b6e5b6cd982f
Create Date: 2026-09-20 16:11:18.566947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a0102b1fba'
down_revision: Union[str, Sequence[str], None] = 'b6e5b6cd982f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('auth_payload_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_connections_account_email'), 'email_connections', ['account_email'], unique=False)
    op.create_index(op.f('ix_email_connections_organization_id'), 'email_connections', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_connections_organization_id'), table_name='email_connections')
    op.drop_index(op.f('ix_email_connections_account_email'), table_name='email_connections')
    op.drop_table('email_connections')
    # ### end Alembic commands ###
