"""add screening and shortlisting columns to applications

Revision ID: fc4a2f7907c7
Revises: e0a0102b1fba
Create Date: 2026-09-20 17:37:51.186575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4a2f7907c7'
down_revision: Union[str, Sequence[str], None] = 'e0a0102b1fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('screening_status', sa.String(length=50), server_default='PENDING', nullable=False))
    op.add_column('applications', sa.Column('screening_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('shortlist_status', sa.String(length=50), server_default='PENDING', nullable=False))
    op.add_column('applications', sa.Column('shortlist_reason', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'shortlisted_at')
    op.drop_column('applications', 'shortlist_reason')
    op.drop_column('applications', 'shortlist_status')
    op.drop_column('applications', 'screening_notes')
    op.drop_column('applications', 'screening_status')
    # ### end Alembic commands ###
