"""create_imported_emails_table

Revision ID: fd34c825c516
Revises: fc4a2f7907c7
Create Date: 2026-09-20 17:47:11.177584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd34c825c516'
down_revision: Union[str, Sequence[str], None] = 'fc4a2f7907c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email_connection_id', sa.Uuid(), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('resumes_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_connection_id'], ['email_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_message_id', name='uq_imported_emails_org_external_id')
    )
    op.create_index(op.f('ix_imported_emails_application_id'), 'imported_emails', ['application_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_candidate_id'), 'imported_emails', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_email_connection_id'), 'imported_emails', ['email_connection_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_external_message_id'), 'imported_emails', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_job_id'), 'imported_emails', ['job_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_organization_id'), 'imported_emails', ['organization_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_sender_email'), 'imported_emails', ['sender_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_emails_sender_email'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_organization_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_job_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_external_message_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_email_connection_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_candidate_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_application_id'), table_name='imported_emails')
    op.drop_table('imported_emails')
    # ### end Alembic commands ###
